name: 'Setup Modern C++ Development Environment'
description: 'Setup Modern C++ Development Environment based on Singularity'
author: 'I (@wx257osn2)'
inputs:
  version:
    description: 'select an image release'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'wx257osn2/cxx_environment'
        path: 'cxx_environment'
    - uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/cxx_environment/cxx.sif
        key: sif-${{ inputs.version }}
    - shell: bash
      run: |
        mv ${{ github.workspace }}/cxx_environment/{run,cxx-env-run}
        rm ${{ github.workspace }}/cxx_environment/bash
        if [ ! -f ${{ github.workspace }}/cxx_environment/cxx.sif ]; then
          curl -sSL -o ${{ github.workspace }}/cxx_environment/cxx.sif https://github.com/wx257osn2/cxx_environment/releases/download/${{ inputs.version }}/cxx.sif
        fi
    - uses: wx257osn2/setup-apptainer@v1.3.6
    - shell: bash
      run: |
        echo "PATH=${PATH}:${{ github.workspace }}/cxx_environment" >> $GITHUB_ENV
        echo "SINGULARITY=apptainer" >> $GITHUB_ENV
