#!/bin/bash

here="$(realpath $(dirname ${BASH_SOURCE:-$0}))"

if [ ! "${SINGULARITY:+true}" ]; then
  if [ `which singularity` ]; then
    SINGULARITY=singularity
  elif [ `which apptainer` ]; then
    SINGULARITY=apptainer
  fi
fi

bash "${here}/setup_overlay.bash"

set -euo pipefail

${SINGULARITY} run --cwd "${PWD}" \
  --overlay "${here}/overlay.img" \
  --bind /usr/share/zoneinfo/Etc/UTC:/usr/share/zoneinfo/Etc/UTC \
  --bind "${PWD}":"${PWD}" \
  --bind "${here}/post_installer":"/installer" \
  "${here}/cxx-$(uname -m).sif" \
  "$@"
