name: Ubuntu

on:
  push:
    branches: [ "**" ]
    tags: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  with_docker:
    strategy:
      matrix:
        include:
          - image: ubuntu-24.04
            arch: x86_64
          - image: ubuntu-24.04-arm
            arch: aarch64
    runs-on: ${{ matrix.image }}
    env:
      cache-key: docker-buildx-cache-${{ matrix.arch }}
    permissions:
      actions: write
    steps:
    - name: remove unused resources
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL $AGENT_TOOLSDIRECTORY /usr/local/share/boost /usr/lib/jvm /usr/share/swift /usr/local/julia /usr/share/kotlinc /usr/local/share/edge_driver /usr/local/share/chromedriver-linux64 /usr/local/share/gecko_driver /usr/share/miniconda /usr/share/sbt /usr/local/share/vcpkg /home/.dotnet/tools /etc/skel/.dotnet/tools /home/linuxbrew /usr/share/apache-maven-* /usr/share/gradle-* /usr/local/.ghcup /home/.nvm /usr/local/share/emacs /usr/local/share/man /usr/local/share/chromium /usr/local/share/powershell /usr/local/share/doc
        docker image prune --all --force
        sudo npm uninstall bazel || true
        sudo npm uninstall bazelisk || true
        rustup self uninstall -y
    - name: stop update man-page
      run: |
        echo "set man-db/auto-update false" | sudo debconf-communicate
        sudo dpkg-reconfigure man-db
    - run: sudo apt update
    - uses: wx257osn2/setup-apptainer@v1.4.4
    - uses: actions/checkout@v5
    - uses: docker/setup-buildx-action@v3
    - uses: actions/cache/restore@v4
      id: cached
      with:
        path: /tmp/.docker-buildx-cache
        key: ${{ env.cache-key }}
    - name: build
      shell: bash
      run: |
        sudo apt install -y --no-install-recommends proot
        if [[ "${{ github.ref }}" = "refs/heads/master" ]]; then
          if [[ "${{ steps.cached.outputs.cache-hit }}" = "true" ]]; then
            export DOCKER_BUILD_EXTRA_OPTIONS="--cache-to type=local,mode=max,dest=/tmp/.docker-buildx-cache-new --cache-from type=local,src=/tmp/.docker-buildx-cache --load"
          else
            export DOCKER_BUILD_EXTRA_OPTIONS="--cache-to type=local,mode=max,dest=/tmp/.docker-buildx-cache-new --load"
          fi
          ./build.bash
          rm -rf /tmp/.docker-buildx-cache
          mv /tmp/.docker-buildx-cache-new /tmp/.docker-buildx-cache
        else
          if [[ "${{ steps.cached.outputs.cache-hit }}" = "true" ]]; then
            export DOCKER_BUILD_EXTRA_OPTIONS="--cache-from type=local,src=/tmp/.docker-buildx-cache --load"
          else
            export DOCKER_BUILD_EXTRA_OPTIONS="--load"
          fi
          ./build.bash
        fi
    - name: remove previous cache
      if: github.ref == 'refs/heads/master' && steps.cached.outputs.cache-hit
      continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh extension install actions/gh-actions-cache
        gh actions-cache delete "${{ env.cache-key }}" --confirm
    - uses: actions/cache/save@v4
      if: github.ref == 'refs/heads/master'
      with:
        path: /tmp/.docker-buildx-cache
        key: ${{ env.cache-key }}
  standalone:
    strategy:
      matrix:
        include:
          - image: ubuntu-24.04
            arch: x86_64
          - image: ubuntu-24.04-arm
            arch: aarch64
    runs-on: ${{ matrix.image }}
    steps:
    - name: stop update man-page
      run: |
        echo "set man-db/auto-update false" | sudo debconf-communicate
        sudo dpkg-reconfigure man-db
    - run: sudo apt update
    - uses: wx257osn2/setup-apptainer@v1.4.4
    - uses: actions/checkout@v5
    - name: build
      shell: bash
      run: |
        bash build.bash
    - id: check-tag
      run: |
        if [[ ${{ github.ref }} =~ ^refs/tags/v[1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$ ]]; then
          echo "deploy-needed=true" >> $GITHUB_OUTPUT
        fi
    - uses: actions/upload-artifact@v4
      if: steps.check-tag.outputs.deploy-needed == 'true'
      with:
        name: sif-${{ matrix.arch }}
        path: ./cxx-${{ matrix.arch }}.sif
  deploy-x86_64:
    runs-on: ubuntu-24.04
    needs: standalone
    if: startsWith(github.ref, 'refs/tags/v2')
    permissions:
      packages: write
    steps:
    - id: check-tag
      run: |
        if [[ ${{ github.ref }} =~ ^refs/tags/v[1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$ ]]; then
          echo "deploy-needed=true" >> $GITHUB_OUTPUT
        fi
    - uses: wx257osn2/setup-apptainer@v1.4.4
      if: steps.check-tag.outputs.deploy-needed == 'true'
    - uses: actions/download-artifact@v5
      if: steps.check-tag.outputs.deploy-needed == 'true'
      with:
        name: sif-x86_64
    - run: echo -n $GITHUB_TOKEN | apptainer registry login --username ${{ github.actor }} --password-stdin oras://ghcr.io
      if: steps.check-tag.outputs.deploy-needed == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        version=${REF##refs/tags/}
        apptainer push cxx-x86_64.sif oras://ghcr.io/wx257osn2/cxx_environment:${version}-x86_64
      if: steps.check-tag.outputs.deploy-needed == 'true'
      env:
        REF: ${{ github.ref }}
  deploy-aarch64:
    runs-on: ubuntu-24.04-arm
    needs: standalone
    if: startsWith(github.ref, 'refs/tags/v2')
    permissions:
      packages: write
    steps:
    - id: check-tag
      run: |
        if [[ ${{ github.ref }} =~ ^refs/tags/v[1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$ ]]; then
          echo "deploy-needed=true" >> $GITHUB_OUTPUT
        fi
    - uses: wx257osn2/setup-apptainer@v1.4.4
      if: steps.check-tag.outputs.deploy-needed == 'true'
    - uses: actions/download-artifact@v5
      if: steps.check-tag.outputs.deploy-needed == 'true'
      with:
        name: sif-aarch64
    - run: echo -n $GITHUB_TOKEN | apptainer registry login --username ${{ github.actor }} --password-stdin oras://ghcr.io
      if: steps.check-tag.outputs.deploy-needed == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        version=${REF##refs/tags/}
        apptainer push cxx-aarch64.sif oras://ghcr.io/wx257osn2/cxx_environment:${version}-aarch64
      if: steps.check-tag.outputs.deploy-needed == 'true'
      env:
        REF: ${{ github.ref }}
  deploy:
    runs-on: ubuntu-24.04
    needs:
      - deploy-x86_64
      - deploy-aarch64
    if: startsWith(github.ref, 'refs/tags/v2')
    permissions:
      contents: write
    steps:
    - id: check-tag
      run: |
        if [[ ${{ github.ref }} =~ ^refs/tags/v[1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$ ]]; then
          echo "deploy-needed=true" >> $GITHUB_OUTPUT
        fi
    - run: |
        version=${REF##refs/tags/}
        echo '```' > release_notes
        echo "$ singularity pull oras://ghcr.io/wx257osn2/cxx_environment:${version}-x86_64 && mv cxx_environment_${version}-x86_64.sif cxx-x86_64.sif # or" >> release_notes
        echo "$ singularity pull oras://ghcr.io/wx257osn2/cxx_environment:${version}-aarch64 && mv cxx_environment_${version}-aarch64.sif cxx-aarch64.sif" >> release_notes
        echo '```' >> release_notes
      if: steps.check-tag.outputs.deploy-needed == 'true'
      env:
        REF: ${{ github.ref }}
    - uses: softprops/action-gh-release@v2
      if: steps.check-tag.outputs.deploy-needed == 'true'
      with:
        body_path: release_notes
