name: Ubuntu

on:
  push:
    branches: [ "**" ]
    tags: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  version-check:
    runs-on: ubuntu-slim
    steps:
    - id: check-tag
      run: |
        if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "action-release=true" >> $GITHUB_OUTPUT
        fi
        if [[ ${{ github.ref }} =~ ^refs/tags/v[1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$ ]]; then
          echo "deploy-needed=true" >> $GITHUB_OUTPUT
        fi
    - uses: actions/checkout@v7
      if: steps.check-tag.outputs.action-release == 'true' || steps.check-tag.outputs.deploy-needed == 'true'
    - parallel:
      - if: steps.check-tag.outputs.action-release == 'true'
        run: |
          tag=$(echo ${{ github.ref }} | sed 's@refs/tags/@@g')
          version=$(grep 'version=v' action.yml | sed 's/ *version=//g')
          if [[ ${tag} != ${version} ]]; then
            echo "${tag} is not match with ${version}, you've forgotten bumping up!!"
            exit 1
          fi
      - if: steps.check-tag.outputs.deploy-needed == 'true'
        run: |
          tag=$(echo ${{ github.ref }} | sed 's@refs/tags/@@g')
          version=$(grep 'version: v' README.md | sed 's/ *version: \(v2[0-9]*\) .*/\1/g')
          if [[ ${tag} != ${version} ]]; then
            echo "${tag} is not match with ${version}, you've forgotten bumping up!!"
            exit 1
          fi
  docker:
    strategy:
      matrix:
        include:
          - image: ubuntu-26.04
            arch: x86_64
          - image: ubuntu-26.04-arm
            arch: aarch64
    runs-on: ${{ matrix.image }}
    needs: version-check
    env:
      cache-key: docker-buildx-cache-${{ matrix.arch }}
    permissions:
      actions: write
    steps:
    - name: stop update man-page
      run: |
        echo "set man-db/auto-update false" | sudo debconf-communicate
        sudo dpkg-reconfigure man-db
    - parallel:
      - name: remove unused resources
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL $AGENT_TOOLSDIRECTORY /usr/local/share/boost /usr/lib/jvm /usr/share/swift /usr/local/julia /usr/share/kotlinc /usr/local/share/edge_driver /usr/local/share/chromedriver-linux64 /usr/local/share/gecko_driver /usr/share/miniconda /usr/share/sbt /usr/local/share/vcpkg /home/.dotnet/tools /etc/skel/.dotnet/tools /home/linuxbrew /usr/share/apache-maven-* /usr/share/gradle-* /usr/local/.ghcup /home/.nvm /usr/local/share/emacs /usr/local/share/man /usr/local/share/chromium /usr/local/share/powershell /usr/local/share/doc /opt/actionarchivecache /opt/az /opt/google-cloud-sdk /opt/hostedtoolcache
          docker image prune --all --force
          sudo npm uninstall bazel || true
          sudo npm uninstall bazelisk || true
          rustup self uninstall -y
      - run: sudo apt update
    - parallel:
      - uses: wx257osn2/setup-apptainer@v1.5.2
      - uses: actions/checkout@v7
      - uses: docker/setup-buildx-action@v4
      - uses: actions/cache/restore@v6
        id: cached
        with:
          path: /tmp/.docker-buildx-cache
          key: ${{ env.cache-key }}
    - name: build
      shell: bash
      run: |
        mkdir -p docker_build
        mv installer docker_build/installer
        ARCH=$(uname -m)
        WIN_ARCH_0=${ARCH//86_/}
        WIN_ARCH=${WIN_ARCH_0//aarch/arm}
        if [[ "${{ github.ref }}" = "refs/heads/master" ]]; then
          if [[ "${{ steps.cached.outputs.cache-hit }}" = "true" ]]; then
            export DOCKER_BUILD_EXTRA_OPTIONS="--cache-to type=local,mode=max,dest=/tmp/.docker-buildx-cache-new --cache-from type=local,src=/tmp/.docker-buildx-cache --load"
          else
            export DOCKER_BUILD_EXTRA_OPTIONS="--cache-to type=local,mode=max,dest=/tmp/.docker-buildx-cache-new --load"
          fi
          docker buildx build -t cxx:latest -f ./Dockerfile --build-arg WIN_ARCH=${WIN_ARCH} ${DOCKER_BUILD_EXTRA_OPTIONS} ./docker_build
          rm -rf /tmp/.docker-buildx-cache
          mv /tmp/.docker-buildx-cache-new /tmp/.docker-buildx-cache
        else
          if [[ "${{ steps.cached.outputs.cache-hit }}" = "true" ]]; then
            export DOCKER_BUILD_EXTRA_OPTIONS="--cache-from type=local,src=/tmp/.docker-buildx-cache --load"
          else
            export DOCKER_BUILD_EXTRA_OPTIONS="--load"
          fi
          docker buildx build -t cxx:latest -f ./Dockerfile --build-arg WIN_ARCH=${WIN_ARCH} ${DOCKER_BUILD_EXTRA_OPTIONS} ./docker_build
        fi
    - name: remove previous cache
      if: github.ref == 'refs/heads/master' && steps.cached.outputs.cache-hit
      continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh extension install actions/gh-actions-cache
        gh actions-cache delete "${{ env.cache-key }}" --confirm
    - uses: actions/cache/save@v6
      if: github.ref == 'refs/heads/master'
      with:
        path: /tmp/.docker-buildx-cache
        key: ${{ env.cache-key }}
  standalone:
    strategy:
      matrix:
        include:
          - image: ubuntu-24.04
            arch: x86_64
          - image: ubuntu-26.04-arm
            arch: aarch64
    runs-on: ${{ matrix.image }}
    needs: version-check
    steps:
    - name: stop update man-page
      run: |
        echo "set man-db/auto-update false" | sudo debconf-communicate
        sudo dpkg-reconfigure man-db
    - parallel:
      - name: remove unused resources
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL $AGENT_TOOLSDIRECTORY /usr/local/share/boost /usr/lib/jvm /usr/share/swift /usr/local/julia /usr/share/kotlinc /usr/local/share/edge_driver /usr/local/share/chromedriver-linux64 /usr/local/share/gecko_driver /usr/share/miniconda /usr/share/sbt /usr/local/share/vcpkg /home/.dotnet/tools /etc/skel/.dotnet/tools /home/linuxbrew /usr/share/apache-maven-* /usr/share/gradle-* /usr/local/.ghcup /home/.nvm /usr/local/share/emacs /usr/local/share/man /usr/local/share/chromium /usr/local/share/powershell /usr/local/share/doc /opt/actionarchivecache /opt/az /opt/google-cloud-sdk /opt/hostedtoolcache
          docker image prune --all --force
          sudo npm uninstall bazel || true
          sudo npm uninstall bazelisk || true
          rustup self uninstall -y
      - run: sudo apt update
    - parallel:
      - uses: wx257osn2/setup-apptainer@v1.5.2
      - uses: actions/checkout@v7
    - name: build
      shell: bash
      run: |
        bash build.bash
    - id: check-tag
      run: |
        if [[ ${{ github.ref }} =~ ^refs/tags/v[1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$ ]]; then
          echo "deploy-needed=true" >> $GITHUB_OUTPUT
        fi
    - uses: actions/upload-artifact@v7
      if: steps.check-tag.outputs.deploy-needed == 'true'
      with:
        name: sif-${{ matrix.arch }}
        path: ./cxx-${{ matrix.arch }}.sif
  push:
    strategy:
      matrix:
        include:
          - image: ubuntu-26.04
            arch: x86_64
          - image: ubuntu-26.04-arm
            arch: aarch64
    runs-on: ${{ matrix.image }}
    needs: standalone
    if: startsWith(github.ref, 'refs/tags/v2')
    permissions:
      packages: write
    steps:
    - id: check-tag
      run: |
        if [[ ${{ github.ref }} =~ ^refs/tags/v[1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$ ]]; then
          echo "deploy-needed=true" >> $GITHUB_OUTPUT
        fi
    - parallel:
      - uses: wx257osn2/setup-apptainer@v1.5.2
        if: steps.check-tag.outputs.deploy-needed == 'true'
      - uses: actions/download-artifact@v8
        if: steps.check-tag.outputs.deploy-needed == 'true'
        with:
          name: sif-${{ matrix.arch }}
    - run: echo -n $GITHUB_TOKEN | apptainer registry login --username ${{ github.actor }} --password-stdin oras://ghcr.io
      if: steps.check-tag.outputs.deploy-needed == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        version=${REF##refs/tags/}
        apptainer push cxx-${{ matrix.arch }}.sif oras://ghcr.io/wx257osn2/cxx_environment:${version}-${{ matrix.arch }}
      if: steps.check-tag.outputs.deploy-needed == 'true'
      env:
        REF: ${{ github.ref }}
  deploy:
    runs-on: ubuntu-slim
    needs: push
    if: startsWith(github.ref, 'refs/tags/v2')
    permissions:
      contents: write
    steps:
    - id: check-tag
      run: |
        if [[ ${{ github.ref }} =~ ^refs/tags/v[1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$ ]]; then
          echo "deploy-needed=true" >> $GITHUB_OUTPUT
        fi
    - run: |
        version=${REF##refs/tags/}
        echo '```' > release_notes
        echo "$ ./pull.bash ${version}" >> release_notes
        echo '```' >> release_notes
      if: steps.check-tag.outputs.deploy-needed == 'true'
      env:
        REF: ${{ github.ref }}
    - uses: softprops/action-gh-release@v3
      if: steps.check-tag.outputs.deploy-needed == 'true'
      with:
        body_path: release_notes
