name: Ubuntu

on:
  push:
    branches: [ "**" ]
    tags: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  with_docker:
    strategy:
      matrix:
        image: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.image }}
    steps:
    - uses: wx257osn2/setup-apptainer@v1.3.6
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: crazy-max/ghaction-github-runtime@v3
    - name: build
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends proot
        DOCKER_BUILD_EXTRA_OPTIONS="--cache-to type=gha,mode=max --cache-from type=gha --load" ./build.bash
  standalone:
    strategy:
      matrix:
        include:
          - image: ubuntu-24.04
            arch: x86_64
          - image: ubuntu-24.04-arm
            arch: aarch64
    runs-on: ${{ matrix.image }}
    steps:
    - uses: wx257osn2/setup-apptainer@v1.3.6
    - uses: actions/checkout@v4
    - name: build
      shell: bash
      run: ./build.bash
    - id: check-tag
      run: |
        if [[ ${{ github.ref }} =~ ^refs/tags/v[1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$ ]]; then
          echo "deploy-needed=true" >> $GITHUB_OUTPUT
        fi
    - uses: actions/upload-artifact@v4
      if: steps.check-tag.outputs.deploy-needed == 'true'
      with:
        name: sif-${{ matrix.arch }}
        path: ./cxx-${{ matrix.arch }}.sif
  deploy:
    runs-on: ubuntu-24.04
    needs: standalone
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
    - id: check-tag
      run: |
        if [[ ${{ github.ref }} =~ ^refs/tags/v[1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$ ]]; then
          echo "deploy-needed=true" >> $GITHUB_OUTPUT
        fi
    - uses: actions/download-artifact@v4
      if: steps.check-tag.outputs.deploy-needed == 'true'
      with:
        name: sif-x86_64
    - uses: actions/download-artifact@v4
      if: steps.check-tag.outputs.deploy-needed == 'true'
      with:
        name: sif-aarch64
    - uses: softprops/action-gh-release@v2
      if: steps.check-tag.outputs.deploy-needed == 'true'
      with:
        files: |
          cxx-x86_64.sif
          cxx-aarch64.sif
